name = "validator"
main = "src/worker.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2023-12-18"

[env.production]
API_URL = "..."

[env.development]
API_URL = "http://localhost:8000"